---
title: "01_Higino"
author: "Gracielle Higino"
date: "2019-10-03"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

I chose the [Roman Emperors database](https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-08-13) from Wikipedia.
```{r load packages, echo=FALSE,results='hide', warning=FALSE,message=FALSE}
# https://gist.github.com/stevenworthington/3178163
ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("ggplot2", "dplyr", "tidyr", "readr")
ipak(packages)
```

# Loading and inspecting the data:
```{r, warnings=FALSE, results='hide'}
emperors <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-08-13/emperors.csv")
```

Inspecting the variables:
```{r}
glimpse(emperors)
```

# Who kills emperors usually?
```{r}
ggplot(data = emperors, aes(x=killer)) +
  geom_bar(stat="count") +
  theme(axis.text.x = element_text(angle = 90))
```


# Arhama: Is there a relation between the emperor rise and who kills him?

```{r}
E = emperors %>%
       select(name,rise,killer)%>%
          arrange (name)
E

ggplot(E, aes(x=killer, col=rise)) +
  geom_point(stat="count") + theme_dark() +theme(axis.text.x = element_text(angle = 90)) 
```




# Are causes of killing related to where do you were born?

```{r}
ggplot(emperors, aes(x=killer, color = birth_prv)) +
  geom_point(stat="count") +
  theme(axis.text.x = element_text(angle = 90))
```

